#!/bin/bash

##########################
#SBATCH --time 48:00:00 #specify a time limit for the job.
#SBATCH --job-name=NM_OF4
#SBATCH --output nm_of4-%j.out
#SBATCH --partition=48hour
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=28
#SBATCH --exclusive
#SBATCH --mail-user=nick.d.martin@northumbria.ac.uk
#SBATCH --mail-type=ALL
##########################

nodes=$SLURM_JOB_NUM_NODES            # Number of nodes
cores=28                              # number of cores

sed -i "/numberOfSubdomains/c\\numberOfSubdomains    $(($nodes*$cores));" system/decomposeParDict

# Run the solution (parallel)
decomposePar -force
mpirun -np $(($nodes*$cores)) simpleFoam -parallel
reconstructPar -latestTime
