#!/bin/bash

##########################
#SBATCH --time 24:00:00 #specify a time limit for the job.
#SBATCH --job-name=NM_OF
#SBATCH --output nm_of-%j.out
#SBATCH --partition=24hour
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=28
#SBATCH --exclusive
#SBATCH --mail-user=nick.d.martin@northumbria.ac.uk
#SBATCH --mail-type=ALL
##########################

nodes=$SLURM_JOB_NUM_NODES            # Number of nodes
cores=28                              # number of cores

mpirun -np $(($nodes*$cores)) simpleFoam -parallel
