#!/bin/bash

foamLog log.simplefoam >/dev/null

gnuplot -persist > /dev/null 2>&1 << EOF
        set logscale y
        set title "Residual vs. Iteration"
        set xlabel "Iteration"
        set ylabel "Residual"
        plot "logs/Ux_0" with lines,\
                "logs/p_0" with lines,\
		"logs/contGlobal_0" with lines,\
		"logs/contCumulative_0" with lines,\
		"logs/k_0" with lines,\
		"logs/omega_0" with lines
EOF
